server: 
  port: 7000
  uri-encoding :  UTF-8
spring: 
  application: 
    name: spring-cloud-zuul
eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:7001/eureka/
        
#hystrix调用方法的超时时间，默认是1000毫秒,如果不调第一次启动会访问会报错，第二中方案是设置不超时hystrix.command.default.execution.timeout.enabled: false
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

zuul:
 host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
 routes: 
    service-a: 
      path: /api-a/**
      serviceId: spring-boot-service-a
      stripPrefix: false #不删除前缀
    service-b: 
      path: /api-b/**
      serviceId: spring-boot-service-b
      stripPrefix: false
    service-c: 
      path: /api-c/**
      serviceId: spring-boot-service-c
      stripPrefix: false

 



 